Overhaul to Ice River mission
OpenHV/OpenHV pull request #1055
Opened 2024-07-18 19:09 UTC by OcelotWalrus

2024-07-19 22:52 UTC, Dzierzan commented
So... patrolling wasn't possible in the end? I am not sure if removing almost all enemy actors was a good idea.

2024-07-20 09:20 UTC, Dzierzan requested changes

2024-07-20 09:20 UTC, Dzierzan commented on mods/hv/maps/ice-river/map.yaml
> +	Actor38: flyingmonster
Nah, don't add force adding critter.

2024-07-20 09:22 UTC, OcelotWalrus commented on mods/hv/maps/ice-river/map.yaml
> +	Actor38: flyingmonster
?

2024-07-20 09:23 UTC, OcelotWalrus commented
> So... patrolling wasn't possible in the end? I am not sure if removing almost all enemy actors was a good idea.

It's possible, but anyway the enemy will periodically produce units. But there can be patrolling units if you want.

2024-07-20 09:30 UTC, Dzierzan commented on mods/hv/maps/ice-river/map.yaml
> +	Actor38: flyingmonster
Remove that critter please.

2024-07-20 09:33 UTC, Dzierzan commented
> > So... patrolling wasn't possible in the end? I am not sure if removing almost all enemy actors was a good idea.
> 
> It's possible, but anyway the enemy will periodically produce units. But there can be patrolling units if you want.

I did like some defenders in the first iteration of this mission. I know AI will use them as soon as it activates. You could technically add 2nd enemy player with the same color with brain dead AI (just enemy with no AI logic applied, kinda like Creep faction), so 1st enemy will never use them. A bit hacky, but it could work.

2024-07-20 09:40 UTC, OcelotWalrus commented
>  I know AI will use them as soon as it activates

The AI won't, as they're ordered to patrol through the script. I added some patrolling units on this force push.

2024-07-20 09:40 UTC, OcelotWalrus commented on mods/hv/maps/ice-river/map.yaml
> +	Actor38: flyingmonster
Done

2024-07-20 09:54 UTC, Dzierzan requested changes

2024-07-20 09:54 UTC, Dzierzan commented on mods/hv/maps/ice-river/map.yaml
> +	Actor37: saucer
Please, remove the saucer.

2024-07-20 09:56 UTC, Dzierzan commented
![image](https://github.com/user-attachments/assets/96261bb4-54c9-4c78-a7f4-36c5d2d1afbd)
Two types of MG pods are available.

2024-07-20 10:04 UTC, Dzierzan commented
Remove AA tank from Factory and Trade Platform. The enemy faction has only one balloon and you can destroy that with electric pods anyway.

I think Repair Tank could be actually readded.

2024-07-20 10:06 UTC, OcelotWalrus commented
Repair Tank hasn't been disabled.

2024-07-20 10:10 UTC, Dzierzan commented
Right, I forgot it's in Utility tab.

2024-07-20 12:32 UTC, OcelotWalrus commented
Is it good for you @Dzierzan ?

2024-07-20 20:01 UTC, Dzierzan commented
AI can build more miners than needed:
![image](https://github.com/user-attachments/assets/0b5eb338-31aa-40c5-8d86-c3a343bb2fe7)

I noticed patrolling enemy units do not attack back.

2024-07-21 10:04 UTC, OcelotWalrus commented
> AI can build more miners than needed:

That's because the periodic productions the AI is ordered to do by the script contain a miner. I don't really see a problem in that in my opinion.

> I noticed patrolling enemy units do not attack back.

That's weird because they do for me. Are you sure you updated your branch?

2024-07-21 17:13 UTC, Dzierzan commented
Then the script needs to take in account having already existing miner unit on the battlefield, can you try to update it? 

Yes, I am sure my branch was up to date.

2024-07-21 17:55 UTC, OcelotWalrus commented
> Then the script needs to take in account having already existing miner unit on the battlefield, can you try to update it?

I'll make so if a miner already exists (because it hasn't been sent as there's no more avaible resource spots), the enemy won't produce it.

> Yes, I am sure my branch was up to date.

They do attack back for me.

https://github.com/user-attachments/assets/490b3dd7-8019-42a2-a21c-9e79e28462d3

2024-07-21 18:00 UTC, OcelotWalrus commented
I understood why they didn't attack you back. When patrolling, units wait a defined amount of time at the waypoint they're in. During that time they can't attack (idk why). So I set that amount to 0 to fix that.

2024-07-22 10:50 UTC, merged