Added new mission: Infiltration Commando
OpenHV/OpenHV pull request #1056
Opened 2024-07-19 10:32 UTC by OcelotWalrus

NOTE: Requires #1055's merge, as it requires the difficulty addons.

2024-07-22 11:17 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/infiltration-commando.lua
> +	Trigger.AfterDelay(8500, function()
```suggestion
	Trigger.AfterDelay(DateTime.Minutes(2) + DateTime.Seconds(30), function()
```

2024-07-22 11:18 UTC, OcelotWalrus commented on mods/hv/maps/infiltration-commando/infiltration-commando.lua
> +	Trigger.AfterDelay(8500, function()
Sure, it's better for human-reading. I'll do that throughout the script.

2024-07-24 15:53 UTC, Dzierzan commented
The game crashes upon building harbor:
![image](https://github.com/user-attachments/assets/f42913c7-8ff5-4c8e-b79d-45133b2a2e4f)

[lua.log](https://github.com/user-attachments/files/16364639/lua.log)

2024-07-24 16:01 UTC, OcelotWalrus commented
That's because you rename mediumboat to mercenaryboat.

2024-07-24 18:12 UTC, Dzierzan commented
I haven't played it after your recent commit, but you sure want to use Merc Boat instead of Torpedo one?

2024-07-25 11:16 UTC, Dzierzan commented
Alright, I've got more feedback:

1. Disable "Money tank", it should be only used in MP, unless there's clear purpose for that in SP mission (like protection or something)

2. It's a huge chokepoint for AI. you might wanna redo that part.
![image](https://github.com/user-attachments/assets/2d33a18f-75f7-4007-80f8-9f993953650c)

Actually, this base has only one entry, no wonder AI had a huge problem here, considering Storage buildings are in another base. I'd make more entries to that base, this should help.
![image](https://github.com/user-attachments/assets/5e1303a0-56e8-4556-97b4-1f3cc3cb82cd)

3. Another huge chokepoint:
![image](https://github.com/user-attachments/assets/8eca3bbe-760f-45e4-a4ae-1408d1bd90d6)
Either give here some gates or redo these parts to gave AI more space.

4. I dunno why you prefer dark maps so much, but they're not so very fun when it comes to visibility. Please, make it brighter.

5. I am not sure if disabling Banshee was a good idea. I mean, I just spammed Copters instead... like a huge spam. And a huge snowball of units is always effective against anything anyway.

2024-07-25 13:39 UTC, OcelotWalrus commented
If you're having trouble completing the mission, you can just check this replay: https://easyupload.io/4ocvgl

2024-07-25 16:59 UTC, Dzierzan commented
Honestly, the way you placed Generators doesn't look too good. I recommend such placement:
![image](https://github.com/user-attachments/assets/663eec0d-7de1-4ca9-b049-9d0a64c75533)

I'd would also add some patrols... maybe some ships and aircraft, what do you think?

2024-07-25 17:14 UTC, OcelotWalrus commented
> Honestly, the way you placed Generators doesn't look too good.

Yeah these placements look better. Thank for pointing that out.

> I'd would also add some patrols... maybe some ships and aircraft, what do you think?

There are actually already air patrols, that regenerate if they're destroyed. I guess I could add naval patrols too.

2024-07-28 17:29 UTC, Dzierzan commented
I'd make more land here, it's a chokepoint due to that bunkers' placement.
![image](https://github.com/user-attachments/assets/70406c5c-28d9-4764-9939-3a27d407eb0a)

2024-07-28 17:44 UTC, Dzierzan commented
I'd maybe rework that part a bit:
![image](https://github.com/user-attachments/assets/985b6257-e209-451b-84ee-5d3bee92a8b1)

2024-07-28 17:45 UTC, Dzierzan commented
Anyway... I think AI spams maybe way too many units, I had to fight against huge army of naval units and I totally forgot about the damn colony. I'd reduce AI naval squad if possible.

2024-07-28 18:10 UTC, OcelotWalrus commented
> I'd make more land here, it's a chokepoint due to that bunkers' placement.
>
> Maybe allign those turrets better?
>
> I'd maybe rework that part a bit:

Yes, indeed.

> Anyway... I think AI spams maybe way too many units, I had to fight against huge army of naval units and I totally forgot about the damn colony. I'd reduce AI naval squad if possible.

Why saying "maybe" if you say after "way too much"? Again, it's supposed to be a hard mission. But I'll reduce the time space between enemy naval squad production: with the current time, it actually produces all the time. But I won't reduce the squad size. Again, the AI won't produce naval units unless the player builds and harbor or has saved the colony. So, just focus on saving the colony first.

2024-07-28 18:53 UTC, Dzierzan commented
So you're saying it's a puzzle mission where building Harbor is not recommended because it aggros AI, despite you encourage the player in building the harbor (secondary objective, lots of water).

Reduce the squad size, you know the solution of your puzzle, potential player won't.

2024-07-28 19:31 UTC, OcelotWalrus commented
I won't say it's a puzzle mission, but one that'll require you to play several times to succeed. I and @Rampoina played the mission and dealing with the naval units while capturing the radar/attack the main base wasn't a problem. If you find it too hard, you can just set the difficulty to easier then. You just gotta produce naval a keep them close to your base to defend.

2024-07-28 20:03 UTC, Dzierzan commented
Ohh believe me, I am not some sunday player, I know my stuff. But I clearly noticed an issue where people might have a problem.

I played it on normal and the amount of units AI had felt like very hard, you had to counter attack with yet equal spam of your units.

> but one that'll require you to play several times to succeed

Sorry, but the way you wrote it does sound like a puzzle mission where you want player to fail in order to do stuff in a correct order.

I do understand the mission is meant to be hard, that's actually great, but there's a thin line between hard mission and frustrating mission. We wanna find golden mean here.

2024-07-29 08:57 UTC, OcelotWalrus commented
I'll reduce the squad size then.
I'd like to know why you fell like it's a "puzzle mission".

2024-07-30 05:30 UTC, Rampoina commented
I didn't feel the naval units were too much of a problem. I kind of agree with @Dzierzan regarding the feel of the mission though.

The intended way to play it is to *rush* to the enemy Radar Dome and take it with a tech, it gives very very little margin for error. If you don't know how to play it you will lose until you figure out you have to do that, and it's like a "puzzle" like @Dzierzan was saying.

The first few times I played it I just didn't understand that and was trying to just beat the AI and take down the power plants, you did improve this a bit by showing the radar dome and telling the player to capture it in-game.

The power plants are shown to the player but are of little importance to stop the airstrikes (they do delay them a bit but it's almost impossible to stop it before losing more than 25%).

> Honestly, the way you placed Generators doesn't look too good. I recommend such placement:

This change actually made it even harder. When the power plants are clumped you can at least destroy a few with a single howitzer salvo but now you can't.

My suggestion is to make destroying the power plants a viable strategy to stall the air strikes. Either massively reduce the amount of generators the AI has or script it directly so that the player has to keep destroying power plants.

Otherwise don't show the power plants to the players at all because it's a red herring.

2024-07-30 09:56 UTC, OcelotWalrus commented
Thanks for that review!
What I'm gonna try to do is make so that the more yuruki power plants are destroyed, the more the airstrikes occur. I'm also gonna edit the Howitzer weapon to make its damage apply to a larger area, so it's more efficient with the new power plant pattern.

2024-07-30 10:36 UTC, OcelotWalrus commented
Should I add some announcer? Like for the reminders and everything.

2024-07-30 16:41 UTC, Dzierzan commented on mods/hv/maps/infiltration-commando/weapons.yaml
> +HowitzerOvercharged:
IMO you shouldn't be modifing Howitzer, unit stats should be rather on paar with MP ones. This makes stuff inconsistent between missions.

2024-07-30 19:12 UTC, OcelotWalrus commented on mods/hv/maps/infiltration-commando/weapons.yaml
> +HowitzerOvercharged:
The problem is that without modifying it, it's not powerful enough for the mission.

2024-08-07 19:03 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .name = Campaign AI
This is already part of
https://github.com/OpenHV/OpenHV/blob/0445cb22de695c6d8d72a7aaf56663766d9fc090/mods/hv/languages/campaign/en.ftl#L1-L3

2024-08-07 20:48 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/map.yaml
> +Translations: hv|languages/difficulty/en.ftl, hv|languages/lua/en.ftl, en.ftl
You are missing the `hv|languages/campaign/en.ftl`

2024-08-11 09:33 UTC, Dzierzan commented on mods/hv/maps/infiltration-commando/weapons.yaml
> +		ImpactSounds: explosion07.ogg, explosion08.ogg
I am still against making howitzer stronger.

2024-08-11 09:37 UTC, Mailaender requested changes

2024-08-11 09:37 UTC, Mailaender commented on mods/hv/languages/lua/en.ftl
> +build-howitzer = Build an Howitzer.
```suggestion
build-howitzer = Build a Howitzer.
```

2024-08-11 09:37 UTC, Mailaender commented on mods/hv/languages/lua/en.ftl
> +build-harbor = Build an Harbor.
```suggestion
build-harbor = Build a Harbor.
```

2024-08-11 09:37 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/weapons.yaml
> +HowitzerOvercharged:
This is still not solved.

2024-08-11 09:37 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/rules.yaml
> +		Briefing: A Synapol mining colony is being threatened by a neraby continental airstrike Yuruki outpost. The basement and its surroundings are extremely well protected by automated defenses, and gro
Extract this string into `.ftl` file.

2024-08-11 09:37 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/infiltration-commando.lua
> +		GroundPatrol = { "mgpod", "mgpod", "electricpod", "mbt", "artillery", "apc", "bike" }
I renamed the pods again so this crashes now. Sorry.

2024-08-11 12:16 UTC, OcelotWalrus commented on mods/hv/maps/infiltration-commando/weapons.yaml
> +		ImpactSounds: explosion07.ogg, explosion08.ogg
I'm gonna test if the mission still works if its armament is the default one.

2024-08-11 12:21 UTC, OcelotWalrus commented
Seems like mission briefings are not supported. I checked and tried everything (map ftl, common ftl, lua ftl...) and it only displays `infiltration-commando-briefing`.

2024-08-11 12:27 UTC, OcelotWalrus commented
Note that your will to make the howitzer have the same armament as default makes the howitzer not really useful as it was designed to be for the mission. It worked well with the older power plant pattern, but not now, if its armament spread is not enhanced.

2024-08-11 13:28 UTC, Mailaender commented
Don't make skirmish weapons inconsistent in single-player. It is irritating and bad design.

2024-08-11 13:51 UTC, Rampoina commented
> Don't make skirmish weapons inconsistent in single-player. It is irritating and bad design.

I mean you can just justify it in mission by saying it's a special powerful howitzer. (and maybe make it bigger or something)

2024-08-11 18:13 UTC, Dzierzan commented
Then it's a backdoor for people for making always custom stuff in missions. And this stuff has to be remembered when changes are made for Skirmish/MP. Hence we're against that.

2024-08-11 18:15 UTC, Dzierzan requested changes

2024-08-11 18:15 UTC, Dzierzan commented on mods/hv/maps/infiltration-commando/rules.yaml
> +		Amount: 200
No, please make it default 120.

2024-08-11 18:23 UTC, Dzierzan commented
BTW the oggs you added are nice and here comes a problem. You've got now two announcers. You could have asked me to do them, then it would be consistent.

2024-08-11 18:51 UTC, OcelotWalrus commented
I can make myself the mission announcer, as I plan on reworking every mission.

2024-08-12 10:18 UTC, Rampoina commented
> Then it's a backdoor for people for making always custom stuff in missions. And this stuff has to be remembered when changes are made for Skirmish/MP. Hence we're against that.

That's kinda the point of campaigns and missions to have special stuff that isn't in the normal multiplayer because it's unique or too strong or whatever else.

2024-08-12 16:21 UTC, Dzierzan commented
> I can make myself the mission announcer, as I plan on reworking every mission. And to be honest I don't really like your announcer, it's too much modified and doesn't sound natural in my opinion.

You can like or not my announcer voice, but the issue with yours is that you've got a conflict with mine now. And it's not meant to sound natural. Think of CnC3 Nod announcer.

Anyway, I'd add custom announcer voices in another PR, when it's established what we all want.

> That's kinda the point of campaigns and missions to have special stuff that isn't in the normal multiplayer because it's unique or too strong or whatever else.

But we don't wanna later keep remembering about custom stuff in missions, it's a small project without huge manpower.

2024-08-12 16:53 UTC, OcelotWalrus commented
> you've got a conflict with mine now

There ain't any conflict.

> you've got a conflict with mine now

I don't see any conflict here.

2024-08-24 13:09 UTC, Mailaender commented on mods/hv/maps/infiltration-commando/rules.yaml
> +		Briefing: infiltration-commando-briefing
Ah sorry, I was wrong. https://github.com/OpenRA/OpenRA/pull/21526 is still not merged.

2024-09-07 16:46 UTC, merged