Added Torpedo Boat unit.
OpenHV/OpenHV pull request #1059
Opened 2024-07-20 11:41 UTC by Dzierzan

- It replaces Medium Boat.
- Medium Boat is kept for potential future use but the unit itself is disabled.

![torpedoboat](https://github.com/user-attachments/assets/fa0b6d78-4452-4e48-861f-45a6dae5ce8b)

2024-07-20 12:34 UTC, OcelotWalrus requested changes

2024-07-20 12:34 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +      Can't attack Pods, Buildings, Vehicles or Air
```suggestion
      Can't attack Ground and Air
```

2024-07-20 12:34 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .description = A boat with torpedo launchers.
```suggestion
   .description = A boat with torpedo pods.
```

2024-07-20 18:28 UTC, WilliamWeberBerrutti commented on mods/hv/languages/rules/en.ftl
> +   .description = A boat with torpedo launchers.
I think torpedo launchers is fine. Using torpedo pods can be confusing because there's an unit category called "Pods" already, and the player might think: "Is it launching units I can control?".

2024-07-20 18:29 UTC, WilliamWeberBerrutti commented on mods/hv/languages/rules/en.ftl
> +      Can't attack Pods, Buildings, Vehicles or Air
This could be a good change, because Harbors are buildings too.

2024-07-20 19:41 UTC, Dzierzan commented on mods/hv/languages/rules/en.ftl
> +   .description = A boat with torpedo launchers.
Yeah, launcher sounds more correct here.

2024-07-21 09:58 UTC, OcelotWalrus approved these changes

2024-07-21 15:18 UTC, merged