Change ECM and Hacker Tanks
OpenHV/OpenHV pull request #1084
Opened 2024-07-29 11:14 UTC by WilliamWeberBerrutti

This PR changes the following:

- removes damage from Hacker Tank projectile
- changes ECM Tank prerequisites to be the same of the Hacker Tank

2024-07-29 11:26 UTC, Mailaender commented on mods/hv/rules/vehicles.yaml
> +		Prerequisites: ~factory.yi, radar, trader
```suggestion
		Prerequisites: ~factory.sc, radar, trader
```

2024-07-29 11:29 UTC, OcelotWalrus commented on mods/hv/rules/vehicles.yaml
> +		Prerequisites: ~factory.yi, radar, trader
ECM tank is for yuruki right?

2024-07-29 11:30 UTC, OcelotWalrus commented on mods/hv/rules/vehicles.yaml
> +		Prerequisites: ~factory.yi, radar, trader
yes he's right. Countermeasure Tank is for synapol, as Hacker Tank is for yuruki.

2024-07-30 04:31 UTC, GraionDilach commented on mods/hv/weapons/energetic.yaml
> -	Warhead@Damage: SpreadDamage
Are you certain this still works?

I haven't checked it ingame yet, but years ago OpenRA couldn't fire weapons at all if they lacked a warhead.

Honestly, I'd just keep this as

```
	Warhead@Damage: SpreadDamage
		ValidTargets: Vulnerability
		Damage: 1
		Spread: 1
		Falloff: 0, 0
```

2024-07-30 10:53 UTC, WilliamWeberBerrutti commented on mods/hv/weapons/energetic.yaml
> -	Warhead@Damage: SpreadDamage
Agreed! Better safe than sorry!

2024-07-30 10:54 UTC, WilliamWeberBerrutti commented on mods/hv/weapons/energetic.yaml
> -	Warhead@Damage: SpreadDamage
What if `Damage: 0` was used?

2024-07-30 10:59 UTC, OcelotWalrus requested changes

2024-07-30 10:59 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +      Disrupts satellite video links\nand obscures the battlefield.
```suggestion
      Disrupts satellite video links
      and obscures the battlefield.
```

2024-07-30 10:59 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +      Jams incoming missiles.
```suggestion
      Deflects incoming missiles.
```

Maybe deflect could be better

2024-07-30 16:16 UTC, GraionDilach commented on mods/hv/weapons/energetic.yaml
> -	Warhead@Damage: SpreadDamage
While I always used `Damage: 1` with other tricks to round it down to 0 during calculations, I can't find anything in the code suggesting me `Damage: 0` wouldn't work directly.

The goal is to have a warhead which satisfies the `Warhead.IsValidAgainst()` call and both options do that.

2024-07-30 16:28 UTC, GraionDilach commented on mods/hv/weapons/energetic.yaml
> -	Warhead@Damage: SpreadDamage
Oh, I see this is resolved now, I just can't mark the discussion as such.

2024-07-31 14:25 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +      Disrupts satellite video links and obscures the battlefield.
```suggestion
      Disrupts satellite video links
      and obscures the battlefield.
```

2024-07-31 21:09 UTC, WilliamWeberBerrutti commented on mods/hv/languages/rules/en.ftl
> +      Disrupts satellite video links and obscures the battlefield.
Does it really need a line break?

2024-07-31 21:42 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +      Disrupts satellite video links and obscures the battlefield.
yeah it does. It'll look too long.

2024-09-03 18:44 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
>     .encyclopedia = The hacker tank contains equipment to penetrate firewalls of individual units and interfer with their command and control software so they will accept orders from the enemy and eng
It should hack the video uplink and obscure the battlefield as stated here.

2024-09-03 23:05 UTC, WilliamWeberBerrutti commented on mods/hv/languages/rules/en.ftl
>     .encyclopedia = The hacker tank contains equipment to penetrate firewalls of individual units and interfer with their command and control software so they will accept orders from the enemy and eng
I'll have to playtest a bit more before resolving this comment.

2024-09-05 16:35 UTC, Rampoina commented
@WilliamWeberBerrutti says it shouldn't be merged yet, he wants to do more tests and some changes.

2024-09-05 17:45 UTC, WilliamWeberBerrutti commented
> @WilliamWeberBerrutti says it shouldn't be merged yet, he wants to do more tests and some changes.

I think it's good now!

2024-09-06 18:10 UTC, merged