Balance Battleship
OpenHV/OpenHV pull request #1096
Opened 2024-07-31 21:03 UTC by WilliamWeberBerrutti

2024-08-01 10:36 UTC, OcelotWalrus commented on mods/hv/rules/aircraft.yaml
> +		Prerequisites: radar, trader, techcenter
You made it available to all factions.

2024-08-01 10:37 UTC, OcelotWalrus commented on mods/hv/rules/aircraft.yaml
> +		Prerequisites: radar, trader, techcenter
You must also add the `~starport.x` prerequisite or it'll still appear even if the player has no starport (if I'm right)

2024-08-07 18:39 UTC, OcelotWalrus requested changes

2024-08-07 18:39 UTC, OcelotWalrus commented on mods/hv/rules/aircraft.yaml
> +		MinRange: 6c0
```suggestion
		MinRange: 8c0
```

From what I've seen, `MinRange` is always the halved value of `Range`.

2024-08-07 18:58 UTC, Mailaender commented on mods/hv/weapons/ballistics.yaml
> -	# BurstDelays: 8
Please merge this into your previous commit.

2024-08-07 21:56 UTC, WilliamWeberBerrutti commented on mods/hv/rules/aircraft.yaml
> +		MinRange: 6c0
It's not always the case, but I think we should change to always be the half of `Range` for all units to be consistant.

2024-08-07 21:59 UTC, merged