Encyclopedia update
OpenHV/OpenHV pull request #1128
Opened 2024-08-06 12:41 UTC by OcelotWalrus

Requires https://github.com/OpenRA/OpenRA/issues/21530 's fix

* Added a new `Pods` label
* Added a new `Tanks` label
* Added a new `Utilities` label
* Added a new `Aircraft` label
* Added a new `Ships` label

2024-08-06 17:13 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +     Weak vs Tanks
Don't duplicate from `.description`. Use https://projectfluent.org/fluent/guide/references.html

2024-08-06 17:17 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
```suggestion
   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 5 tons of cargo, the equivalent of 8 pods. It can also lift one vehicle.
```
In the far future the imperial system is no more.

2024-08-06 17:21 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
```suggestion
   .encyclopedia = The chopper is a heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
```

2024-08-06 17:44 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
why not?

2024-08-07 17:40 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
A ton is an imperial system unit too by the way.

2024-08-07 19:05 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
Ah sorry, in systems where SI is the default, ton means metric ton.

2024-08-07 19:11 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = A reconnaissance air unit.
This is an invitation for lore, I think. How about:
> A disc shaped aircraft with good maneuverability. It is not well suited for combat, which is why it is often used for reconnaissance missions. Due to its unusual shape and low radar reflectance, oftentimes civilians will report this sighting to the authorities first.

2024-08-07 20:36 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The chopper is an heavy transport aircraft, than can load up to 11,000 lbs of cargo, the equivalent of 8 pods. It can also lift one vehicle.
![image](https://github.com/user-attachments/assets/f0676583-a2c2-452d-b7c7-af1ff241366f)

2024-08-08 11:39 UTC, OcelotWalrus commented
Should I fix the crash by removing the other TooltipInfo of the radartank (the one when it's deployed) or wait for the bug to be solved on OpenRA? @Mailaender. I don't think it's critical to not have that TooltipInfo, as it's here just to have "Radar Tank (Deployed)" instead of "Radar Tank".

2024-08-08 14:20 UTC, Mailaender commented
I think it is fair to remove the deployed tooltip.

2024-08-08 14:23 UTC, OcelotWalrus commented
Alright then!

2024-08-09 10:39 UTC, Mailaender requested changes
`e` is not a suitable commit message.

2024-08-09 10:52 UTC, OcelotWalrus commented
> `e` is not a suitable commit message.

A change I forgot to squash :)

2024-08-09 16:51 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The broker pod is an advanced pod, that can hack itself onto an opponent base or storage to analyze the income sources, and remotely steal cash from stock markets.
```suggestion
   .encyclopedia = The broker pod is an advanced pod that can invest in the stock market for a constant stream of revenue. It can also tap into an opponent base or storage and initiate forged wire transfers to remotely steal enemy cash.
```

2024-08-09 16:53 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The mortar pod is a fast support vehicle, armed with a mortar gun, particularly powerful against both pods and buildings. It was designed by the Synapol Corporations to handle smal
```suggestion
   .encyclopedia = The mortar pod is a fast support vehicle, armed with a mortar gun, particularly powerful against both pods and buildings. It was designed by the Synapol Corporations to handle small outpost, often defended with pods only.
```

2024-08-09 16:56 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +     Availability: Universal/Faction design can vary
You can simply put a description on `AATANK2`.

2024-08-09 16:56 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Mobile AA turrets are yet, less powerful than stationary AA turrets, but they can sue the enemy when it gets out of range. While they are a universal unit, factions use different A
"sue the enemy", "universal unit" ???

2024-08-09 16:58 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
>     .name = Transport Tank
```suggestion
   .name = APC
   .generic-name = Transport Tank
```

2024-08-09 16:59 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Transport tanks - commonly known as "APC" (Armored Personal Carrier) - are durable transport units, that can load up to 8 tons of cargo, the equivalent of 5 pods. It is used to tra
```suggestion
   .encyclopedia = Armored Personal Carrier are are durable transport tanks, that can load up to 8 tons of cargo, the equivalent of 5 pods. It is used to carry pods, giving them better protection, while still being able to fire through firing ports. It was designed to conduct assault missions, when you don't have enough resources to produce tanks.
```

2024-08-09 17:00 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The missile tank is a agile tank, able to fire from a turret, while still moving decently fast. It is armed with a powerful missile launcher, extremely powerful against buildings.
```suggestion
   .encyclopedia = The missile tank is an agile tank, able to fire from a turret, while still moving decently fast. It is armed with a powerful missile launcher, extremely powerful against buildings. It is yet less versatile than the railgun tank, it is stronger against buildings.
```

2024-08-09 17:04 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The hacker is the most modern tank of all: it has the ability to fire a laser zap, that changes allegiance of the target unit. The allegiance is permanent, unless it gets out of ra
```suggestion
   .encyclopedia = The hacker tank contains equipment to penetrate firewalls of individual units and interfer with their command and control software so they will accept orders from the enemy and engage in friendly fire. The effective change of allegiance is permanent, until the hacker tank gets destroyed or changes the target. It can only have one controlled unit at a time. It can also obscure the opponent's battlefield on a small region when deployed.
```

2024-08-09 17:06 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The countermeasure tank is the most modern tank of all: it has the ability to beam, that disables units for a brief moment. It also deflects incoming missiles.
```suggestion
   .encyclopedia = The electronic countermeasure (ECM) tank can overload enemy weapon systems with a controlled beam that disables all electronic system units for a brief moment disabling them completely. The effect only lasts a few seconds. It also deflects incoming missiles.
```

2024-08-09 17:08 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The mercenary tank is a generic tank, that can be only obtained through the drop zone buildings. It has though no turret, like other main battle tanks.
```suggestion
   .encyclopedia = The mercenary tank is a generic tank, that can be only obtained through the drop zone buildings. It has a double barralled canon that can't rotate.
```

2024-08-09 17:11 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = This vehicle is an upgrade of the artillery tank. It is twice bigger, has more range, and fires two bombshells at once. Its range is extremely higher, and it is damaging against an
```suggestion
   .encyclopedia = This vehicle is an upgrade of the artillery tank. It is twice bigger, has more range, and fires two bombshells at once. Its range is extremely high, and it is damaging against any type of armor. Due to intellectual property disputes, this design is rarely seen on the battlefield.
```

2024-08-09 17:13 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The naval minelayer is able to lay smart mines than explode on enemy units, while avoiding ally units. It can also detect enemy units at a certain range. It has to reload at an har
```suggestion
   .encyclopedia = The naval minelayer is able to lay smart mines that explode on enemy units, while avoiding ally units. The mines can also be triggered manually. Minelayers can also detect enemy mines at a certain range. It has to reload at an harbor.
```

2024-08-09 17:14 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The minelayer is a fast and agile support unit, that can lay smart mines, that explode on enemy units; while avoiding ally units. It also has the ability to detect enemy mines at a
```suggestion
   .encyclopedia = The minelayer is a fast and agile support unit, that can lay smart mines, that explode on enemy units; while avoiding ally units. They can also be triggered manually. It also has the ability to detect enemy mines at a certain range. It has to reload on trade platforms.
```

2024-08-09 17:15 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = The money transport moves cash to other players, in order to help them.
```suggestion
   .encyclopedia = The money transport moves cash to other players, in order to help them financially.
```

2024-08-09 17:44 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Mobile AA turrets are yet, less powerful than stationary AA turrets, but they can sue the enemy when it gets out of range. While they are a universal unit, factions use different A
"Sue the enemy" as "pursue the enemy". By "universal unit" I meant that every faction uses it, but the armaments are different.

2024-08-09 17:47 UTC, Mailaender commented on mods/hv/rules/vehicles.yaml
> +	-Encyclopedia:
You also have an entry for both shocker and rocket pod.

2024-08-09 21:49 UTC, Mailaender commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Mobile AA turrets are yet, less powerful than stationary AA turrets, but they can sue the enemy when it gets out of range. While they are a universal unit, factions use different A
Sue means to bring to justice in court. It is not a universal unit. There are different ones per faction.

2024-08-11 06:51 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Mobile AA turrets are yet, less powerful than stationary AA turrets, but they can sue the enemy when it gets out of range. While they are a universal unit, factions use different A
Sue can mean more than bring to justice in court. I studied literature in high school, thanks. But if you prefer I can put pursue.

2024-08-11 06:52 UTC, OcelotWalrus commented on mods/hv/languages/rules/en.ftl
> +   .encyclopedia = Mobile AA turrets are yet, less powerful than stationary AA turrets, but they can sue the enemy when it gets out of range. While they are a universal unit, factions use different A
I know, I set two different encyclopedia entries at last push.

2024-08-11 08:40 UTC, merged