Add pre-spawn clouds function to CloudSpawner
OpenHV/OpenHV pull request #178
Opened 2020-08-30 13:27 UTC by dnqbob

2020-08-30 14:05 UTC, dnqbob commented
Wait a second until I pass this bot test

2020-08-30 14:42 UTC, dnqbob commented
done

2020-09-05 08:04 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/World/CloudSpawner.cs
> +				var startEdge = target - (world.Map.DistanceToEdge(target, -delta) + info.Cordon).Length * delta / 1024;
The calculation of `world.Map.DistanceToEdge(target, -delta) + info.Cordon).Length * delta / 1024` can be cached here and in `var startEdge = target - (self.World.Map.DistanceToEdge(target, -delta) + info.Cordon).Length * delta / 1024`. Same for the positive `delta` variant.

2020-09-05 08:05 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/World/CloudSpawner.cs
> +			var direction = WAngle.FromFacing(facing);
This variable is unused.

2020-09-05 08:07 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/World/CloudSpawner.cs
> +             *              |_____|
I really like the ASCII art drawing here. It only looks broken on GitHub because these lines are space intended.

![image](https://user-images.githubusercontent.com/756669/92300949-980ad600-ef5f-11ea-9b2b-0c83a995917f.png)

2020-09-05 10:56 UTC, Mailaender requested changes

2020-09-05 10:56 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/World/CloudSpawner.cs
> +				var animation = new Animation(world, info.Image, () => WAngle.FromFacing(facing));
I assume this is where you wanted to use `direction`.

2020-09-05 15:29 UTC, Mailaender approved these changes
Awesome. This adds some really nice polish.

2020-09-05 15:29 UTC, merged