Add air-transport squad / repair-squad for AI
OpenHV/OpenHV pull request #789
Opened 2023-09-15 03:19 UTC by dnqbob

2023-09-24 10:31 UTC, Mailaender commented on mods/hv/rules/bots.yaml
> +	CashTrickler@HardAI:
I don't want cheating AI.

2023-09-24 10:31 UTC, Mailaender commented on mods/hv/rules/bots.yaml
> -	ModularBot@RogueAI:
It is just one AI on purpose for easier maintenance and because they are in fact all the same.

2023-09-24 10:33 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			ManagerRunning = true;
Why are you not using `world.IsReplay` then?

2023-09-24 10:33 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
Why are you not using `world.IsReplay` then?

2023-09-24 10:34 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +		public bool ManagerRunning { get; private set; }
Why are you hard-coding trait fields here?

2023-09-24 10:35 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +	[Desc("Allows the player to issue the orders from actors with " + nameof(IssueOrderToBot) + ".")]
This seems to be conceptually wrong. Each bot module should use `bot.QueueOrder` not another trait.

2023-09-24 10:39 UTC, Mailaender commented
Can you please not put everything into one huge pull request? Split this off. `No ShakeOnDeath for Landed Pod` is completely unrelated. The code changes seem very problematic, but `Increase aatank building rate for AI` and `BuildingDelays for tech building` seem like a good idea.

2023-09-24 10:41 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/SendUnitToAttackBotModule.cs
> +			// TODO: if Open-HV is going to have disguising unit which needs AI support,
That is not planned.

2023-09-24 10:43 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/SendUnitToAttackBotModule.cs
> +			// and we divide preparing stage, disguising stage and attacking stage for PERF.
There is no disguise in OpenHV.

2023-09-24 10:45 UTC, Mailaender commented on mods/hv/rules/bots.yaml
> +		Condition: enable-easy-ai
I doubt this one will be easier, just less capable.

2023-09-24 10:47 UTC, Mailaender requested changes
Please avoid hacks and submit this in smaller pieces.

2023-09-24 11:36 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
because `BotTick is running can cover all three conditions I list here, and I am not sure we can use `world.IsReplay` to check the replay for loading game.

2023-09-24 11:46 UTC, dnqbob commented on mods/hv/rules/bots.yaml
> -	ModularBot@RogueAI:
Sure, then I will delete those AI

2023-09-24 11:46 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
If we cannot check loading saved game, `IssueOrderToBot` will add order to list endlessly while loading the game, which will result in ill behaviours when loading is done.

2023-09-24 11:49 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +		public bool ManagerRunning { get; private set; }
I guess you means `ManagerRunning`, `ManagerRunning` is ensure the bot tick is running and stop `IssueOrderToBot` add orders while it cannot consume.

2023-09-24 12:01 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +	[Desc("Allows the player to issue the orders from actors with " + nameof(IssueOrderToBot) + ".")]
The idea is: 
1. When actors with `IssueOrderToBot` have certain condition, it can use `IssueOrderToBot` to require bot player to give it an order.
2. `ExternalBotOrdersManager` recieve the requirement and give it an order.

It is a cheap way (compared to search the actors in world and give orders) to perform control in detail, and very flexible.

2023-09-24 12:09 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +	[Desc("Allows the player to issue the orders from actors with " + nameof(IssueOrderToBot) + ".")]
Idk if you agree with my explanation above. I think there maybe some misunderstandings in the description, but I am unable to think of better one on this.

2023-09-24 12:10 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/SendUnitToAttackBotModule.cs
> +			// TODO: if Open-HV is going to have disguising unit which needs AI support,
Then I will also remove the one in `AttackOptions`.

2023-09-24 12:19 UTC, dnqbob commented on mods/hv/rules/bots.yaml
> +	CashTrickler@HardAI:
Without cheat AI, we will need AI's base management and strategy planning closed to human, or it will be easy to be defeated.

Current AI doesn't reach this level.

2023-09-24 13:39 UTC, dnqbob commented on mods/hv/rules/bots.yaml
> +	CashTrickler@HardAI:
Anyway, if you don't need different AI then it can be deleted.

2023-09-24 14:05 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
I find we can use `World.IsLoadingGameSave`, but I stick to just check if `BotTick` running, which is more simple and understandable.

2023-09-24 14:42 UTC, dnqbob commented
Remove unrelated commits and different AI are removed.
`SendUnitBotModule` remove the disguise related.

The remaining commits are related. `Increase aatank building rate for AI` and `BuildingDelays for tech building` is to make bot player not die too fast in AI test, or you will have to restart the game for several times to see the AI change.

2023-09-29 18:25 UTC, Mailaender commented
I meant you should submit them in their own easier to digest pull request not to ditch them.

2023-09-29 23:11 UTC, dnqbob commented
I will PR them later afte this is merged. Some commits like different AI focus on comparison those new bot module, they can be dropped and easy to re-write. 

I thought this PR was huge so I made it focus on bot module related.

2023-09-29 23:34 UTC, dnqbob commented
In addition, the "enable air-trans for AI" requires all changes in those bot module, only except the "LoadCargoBotModule up-to-date". I quite don't want to split air-transpot squad into a PR of "has dependcies" for hard to maintain when I need to change the bot module.

2023-10-01 17:05 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
I found some interesting stuff in "ModularBot.cs":
1. Bot tick check if it should be actived only on host, at line 63 comment.
2. Bot tick is only actived when the game is not replay, at line 64.
3. Bot tick need the game is not `World.IsLoadingGameSave`, at line 86.

Therefore, my method here to check if bot tick is running is correct. We don't need any other checks, unless we move the checks to `IssueOrderToBot` and remove `IsManagerRunning`. Again, I don't think that is a good idea on both code maintaining and perf.

2023-10-01 17:15 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +		public bool ManagerRunning { get; private set; }
If we don't add the trait field `ManagerRunning`, then we need to add  `Game.IsHost || World.IsReplay || World.IsLoadingGameSave` to replace `ManagerRunning` in `IssueOrderToBot`. 

I don't think that is a good idea, for there is no trait on regular actor should care about those fields, which looks like they may cause desync. `ManagerRunning` is more acceptable in this case.

2023-10-02 05:58 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +	[Desc("Allows the player to issue the orders from actors with " + nameof(IssueOrderToBot) + ".")]
I mean the actors should not request to be ordered around. The bot player should both decide what action to do and order it. See also this change https://github.com/OpenHV/OpenHV/commit/7f8833febb23e98bc6ef6569bf7d0d47c77d76eb where I removed a similar hack.

2023-10-02 06:01 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
You are relying on `ModularBot` to behave this way and hope that it stays. It is better to directly check against `IsLoadingGameSave` and `IsReplay` instead. Also keeps the code readable by itself.

2023-10-02 06:02 UTC, Mailaender commented on mods/hv/rules/bots.yaml
> +			uplink: 9000
This is a good idea. Can you submit it separately?

2023-10-02 06:04 UTC, Mailaender commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +		public bool ManagerRunning { get; private set; }
Another reason to get rid of this trait.

2023-10-02 06:41 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
I mean all `IBot.BotTick` only runs by `ModularBot`, nowhere else.  So `BotTick` is running <=> `ModularBot.ITick` is fully functional <=> The game is not host, not replay and not in loading. From logic it is correct.

2023-10-02 07:10 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
Even if we need to add `Game.IsHost || World.IsReplay || World.IsLoadingGameSave`, it should never be put inside the `IBot.BotTick`, it is superfluous.

2023-10-03 16:33 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +			// 1. not a replay
Plus, if let us assume my thought that
> relying on `ModularBot` to behave this way

has flaws.

Then, yeah, we should add those checks to `IBot.BotTick` in `ExternalBotOrdersManager`, **and should not we add those checks to all other bot modules that use `IBot.BotTick`**? And why they don't even need that?

2023-10-03 16:51 UTC, dnqbob commented on OpenRA.Mods.HV/Traits/BotModules/ExternalBotOrdersManager.cs
> +	[Desc("Allows the player to issue the orders from actors with " + nameof(IssueOrderToBot) + ".")]
Btw, I also think https://github.com/OpenHV/OpenHV/commit/7f8833febb23e98bc6ef6569bf7d0d47c77d76eb is a good change but I prefer the reason that actors belong to AI should at least request order to hope the player to change itself, instead of directly changing itself by using activity. 

It is a matter of fair micro-manage of the order lantency in network. We all know that if the server is not good and order lantency >10 ticks, then actor change based on the order given will have a latency of >10 ticks.  

However, if actor change itself by using activity directly, there is no latency. This will be very unfair to players if they play against AI in mutiplayer.

2023-10-08 09:49 UTC, Mailaender commented on mods/hv/rules/bots.yaml
> +			uplink: 9000
Please rebase onto https://github.com/OpenHV/OpenHV/pull/800.

2023-10-08 09:53 UTC, Mailaender commented
Thanks for your submission, but I don't want units ordering themselves around using a bot module relay.

2023-10-08 09:53 UTC, closed without merging