Draft: Pods Refining
OpenHV/OpenHV pull request #887
Opened 2023-12-26 21:01 UTC by WilliamWeberBerrutti

This PR attempts to fix https://github.com/OpenHV/OpenHV/issues/885, https://github.com/OpenHV/OpenHV/issues/877 and contemplates this discussion https://github.com/OpenHV/OpenHV/discussions/879.

2023-12-30 21:30 UTC, Mailaender commented on mods/hv/rules/pods.yaml
> +	# 	BuildPaletteOrder: 6
```suggestion
	 Buildable:
	 	Queue: Pod
	 	Description: Financial analyst.\nInvests into stock market for dividents.\n  Unarmed
	 	Prerequisites: ~disabled
	 	BuildPaletteOrder: 6
```

2023-12-30 21:31 UTC, Mailaender commented on mods/hv/rules/pods.yaml
> +	# 	BuildPaletteOrder: 6
Also, don't mix tabs and spaces.

2023-12-30 21:31 UTC, Dzierzan commented on mods/hv/rules/buildings.yaml
> +		Prerequisites: techcenter
Keep it for SC for now. I'll provide new utility vehicle which will replace Broker Pod.

2023-12-30 21:36 UTC, Dzierzan requested changes

2023-12-30 21:36 UTC, Dzierzan commented on mods/hv/rules/pods.yaml
> +	# Disabled for now, for skirmish and multiplayer games
Revert those changes. I'll provide new utility vehicle which will replace Broker Pod.

2023-12-30 21:36 UTC, Dzierzan commented on mods/hv/rules/buildings.yaml
> +		Prerequisites: techcenter
Keep it for SC for now. I'll provide new utility vehicle which will replace Broker Pod.

2023-12-30 21:36 UTC, Dzierzan commented on mods/hv/rules/pods.yaml
> +		Description: Fast scout vehicle.\nShoots surface to air/ground electricity.\n  Strong vs Tanks and Aircraft\n  Weak vs Pods
Well, naming it a scout is too much IMO. I mean it's too big to be the scout. Maybe `Support vehicle`?

2023-12-30 21:41 UTC, Dzierzan requested changes

2023-12-30 21:41 UTC, Dzierzan commented on mods/hv/weapons/energetic.yaml
> +		Inaccuracy: 0
`EnergyBolt` doesn't have parameters `Arm` and `Inaccuracy`. Remove those two, please.

2024-01-02 19:46 UTC, WilliamWeberBerrutti commented on mods/hv/rules/pods.yaml
> +	# Disabled for now, for skirmish and multiplayer games
As we discussed in the Matrix channel, if I understood correctly, for now, I'll allow both factions to build Ore Smelters.

2024-01-02 19:46 UTC, WilliamWeberBerrutti commented on mods/hv/rules/buildings.yaml
> +		Prerequisites: techcenter
As we discussed in the Matrix channel, if I understood correctly, for now, I'll allow both factions to build Ore Smelters.

2024-01-02 19:57 UTC, Dzierzan commented
Maybe it would be better to squash all commits but have one detailed description. @Mailaender your thoughts about this?

2024-01-02 20:04 UTC, Mailaender commented
You don't have to squash this. I can do it during merge, but single commits make it more readable.

2024-01-02 20:07 UTC, Mailaender commented on mods/hv/rules/pods.yaml
> +		Description: Field technician.\nInfiltrates and captures enemy structures.\nHeals pods.\n  Unarmed
```suggestion
		Description: Field technician.\nInfiltrates and captures enemy structures.\nRepairs pods.\n  Unarmed
```

2024-01-02 20:24 UTC, merged